name: "E-Ink React Dashboard Add-on"
description: "Visualize Home Assistant data as a react page for the use on E-Ink displays"
version: "2024.12.2"
slug: "e-ink-react-dashboard"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386