name: "E-Ink React Dashboard Add-on
version: 1.0.1"
slug: "e-ink-react-dashboard"
description: "Visualize Home Assistant data as a react page for the use on E-Ink displays"
url: "https://github.com/leonherrmann/e-ink-react-dashboard"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
ports:
  8000/tcp: 8000